### ISSUE TITLE
Location Eingabe schlägt fehl

### ISSUE THREAD

**Issue by 191977** [alexplusde/events#20]
Hi Alex, 
sehr schönes addon, teste es gerade. Komme aber im Moment nicht weiter, weil folgender Fehler auftritt:
Bei der Eingabe einer Location lande ich bei Klick auf "Hinzufügen" auf der leeren Loacation-Tabelle. Bei Klick auf "Übernehmen" kommt 
![Bildschirmfoto 2020-04-22 um 21 29 43](https://user-images.githubusercontent.com/47699885/80026684-d3da5d00-84e2-11ea-882b-36f3ac9f7a08.png)
Log:
22.04.2020 20:36:54 | Error | Call to a member function getUid() on null | redaxo/src/addons/events/boot.php | 198

Gleicher Fehler beim editieren der Tabelle im Table Manager: 
![Bildschirmfoto 2020-04-22 um 21 37 30](https://user-images.githubusercontent.com/47699885/80026833-11d78100-84e3-11ea-81fa-1ed44cf00b95.png)

**Comment by alexplusde** [comment]
Hast du die Version aus dem installer oder GitHub Master verwendet?

**Comment by 191977** [comment]
Installer, soll ich mal repo?

**Comment by alexplusde** [comment]
Ja, bitte.

**Comment by 191977** [comment]
Ok, lüppt ohne zu murren!

**Comment by 191977** [comment]
Danke dir herzlich! Melde mich wieder wenn beim testen was hochkommt.

**Comment by alexplusde** [comment]
Ich sollte wohl ein Update rausbringen...
