### ISSUE TITLE
Enddatum Format YYYY-MM-DD

### ISSUE THREAD

**Issue by 191977** [alexplusde/events#21]
Field endDate format DD.MM.YYYY wird gespeichert aber bei Aufruf nicht dargestellt und dann mit 00... überschrieben.
Alex mach du bitte, dann kann ich an deinem commit vllt nachvollzeihen auf was man bei so einer Änderung achten muss.

**Comment by alexplusde** [comment]
Ich fürchte, YForm Date-Felder lassen sich nicht ordentlich konfigurieren, dass sie mit HTML5-Eingabe und mit schöner Datumsausgabe in der Liste korrekt funktionieren. Ich habe keine gültige Kombination gefunden, die das erfüllt. Entweder ist eine Korrektur in YForm erforderlich, oder wir duplizieren das Feld und machen es selbst.

**Comment by 191977** [comment]
Ich habe das Ende-Datum jetzt einfach mal wie das Start-Datum eingestellt und es funktioniert soweit jetzt im Moment. Das Problem ist dann die Darstellung in der Tabellenansicht?

**Comment by alexplusde** [comment]
Genau. Hierauf haben wir keinen Einfluss, deswegen müssen wir ein value dafür abwandeln oder es in YForm fixen

**Comment by 191977** [comment]
Ok. Das ist noch etwas über meiner gehaltsstufe :-) Ich würde das Ende-Datum fürn Moment auf jeden Fall wie das Startdatum einstellen, so läuft es wenigstens und man hat nur kosmetische Probleme.

**Comment by alexplusde** [comment]
Dann lassen wir hier offen, ich kümmere mich um die Kosmetik.

**Comment by alxndr-w** [comment]
Habe hier keinen Fehler mehr feststellen können. Könnte in YForm direkt gefixt worden sein.

Mindestanforderungen sind jetzt YForm 4.0
