### ISSUE TITLE
Feldbechreibungen glatt ziehen

### ISSUE THREAD

**Issue by 191977** [alexplusde/events#22]
zB "Beginn" für Startdatum und Startzeit. 
Kann ich mir anschauen wenn ich das Zusammenspiel yForm fields und event addon durchstiegen habe. Ich warte dazu mal issue #21 ab

**Comment by alexplusde** [comment]
Die Eingabe sollte in meinen Augen abhängig sein vom Termin: ganztägig sollte Uhrzeiten ausblenden, Endzeiten optional sein. Wie würdest du es lösen?

**Comment by 191977** [comment]
Ja hört sich gut, das würde ich nur in einen weiteren Issue auslagern. #23

**Comment by alxndr-w** [comment]
Ist glaube ich erledigt.
