### ISSUE TITLE
Umgang mit UID

### ISSUE THREAD

**Issue by 191977** [alexplusde/events#25]
Es sieht für mich so aus, als bietet der Vendor für iCal/ICS keine Methode um die UID extern zu generieren und an diesen zu übergeben. Jede ICS bekommt eine neue UID mit der der Standard-php-Methode uniqid(). Es gibt aber auch schon einen entsprechenden issue dazu https://github.com/markuspoerschke/iCal

Es scheint auch ganz allgemein verschiedene Auffassungen dazu zu geben ob die UID unique zum Event oder zum exportierten file sein soll. Ich verstehe RFC5545 so, dass es zum Event sein müsste. Wir würden dann nach einer bestimmten Logik die UID generieren, in die DB speichern und an den verdor beim Export übergeben. Jedoch scheinen viele Cal-Server so vorzugehen wie der vendor und bei jedem Export eines Kalenders oder Events eine neue UID zu generieren. 
Kannst du dir das bitte auch mal anschauen Alex?

**Comment by alexplusde** [comment]
https://github.com/markuspoerschke/iCal/pull/70#issuecomment-224839888

Soll wohl bei der Initialisierung möglich sein, diese zu übergeben.

**Comment by 191977** [comment]
Ok super danke. Läuft.

**Comment by alexplusde** [comment]
Tipp: Wenn du es fixt, dann verweise in deinem Commit mit `closes #25`. Das Issue geht dann – und erst dann – zu, wenn die Änderung auch wirklich drin ist.
