### ISSUE TITLE
SQL error: Error while executing statement "update rex_event_date set uid = uuid() where uid =""" using params []

### ISSUE THREAD

**Issue by thorol** [alexplusde/events#63]
Bei der Installation des Addons bekomme ich folgenden Fehler:

AddOn events konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "update rex_event_date set uid = uuid() where uid =""" using params []! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uid' in 'field list'

<details>
<summary>System report (REDAXO 5.17.1, PHP 8.2.24, MariaDB 11.4.2)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.17.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.2.24                         |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                |
| ------------: | :------------- |
|       Version | MariaDB 11.4.2 |
| Character set | utf8mb4        |

| Server        |                |
| ------------: | :------------- |
|            OS | Linux          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.62  |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/129.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | no               |

| Packages                  |            |
| ------------------------: | :--------- |
|              2factor_auth | 2.3        |
|             arttec_helper | 3.10.0     |
|               auto_delete | 1.0.2      |
|                    backup | 2.9.1      |
|                  be_style | 3.4.1      |
|       be_style/customizer | 3.3.1      |
|           be_style/redaxo | 3.4.1      |
|                      cke5 | 6.1.0      |
|                   cronjob | 2.11.0     |
|    cronjob/article_status | 2.10.0     |
|   cronjob/optimize_tables | 2.10.0     |
|                 developer | 3.9.2      |
|                 gridblock | 1.1.13     |
| gridblock/contentsettings | 1.7.1      |
|    gridblock/synchronizer | 1.0        |
|                   install | 2.12.1     |
|               maintenance | 3.2.1      |
|                    mblock | 3.4.13     |
|             media_manager | 2.16.0     |
|                 mediapool | 2.14.0     |
|                  metainfo | 2.11.0     |
|                     mform | 8.0.4      |
|                     neues | 5.0.1      |
|                 phpmailer | 2.13.1     |
|                   project | dev        |
|                     sprog | 1.5.1      |
|                 structure | 2.17.1     |
|         structure/content | 2.17.1     |
|         structure/history | 2.17.0     |
|                     users | 2.11.0     |
|                     yform | 4.2.1      |
|               yform/email | 4.2.1      |
|             yform/manager | 4.2.1      |
|               yform/tools | 4.2.1      |
|               yform_field | 2.7.1      |
|             yform_geo_osm | 1.2.9      |
|                  yrewrite | 2.10.0     |
|  yrewrite_domain_settings | 2.2.0      |

</details>

**Comment by thorol** [comment]
Die Felder sind jedoch auch in der install.php auskommentiert, habe ich gerade gesehen, soll das so?
![image](https://github.com/user-attachments/assets/04ad0af5-8666-472e-8bd6-2a185a6cad3e)

**Comment by alxndr-w** [comment]
https://github.com/alexplusde/events/commit/a4293a4c8f919295eb4940e3bd47bdd81f4e416a#diff-19e3c84c1b3ce87245588ae6ee7791fe3b94c98a8f955ea3e89f9f5865144ca0R3-R5

Fix ist auf GitHub, aber noch nicht im Installer. Danke für den Hinweis!

**Comment by thorol** [comment]
Weiß nicht, ob das bei einer neuen Installtion hilft, denn die oben erwähnt Änderung war bereits in meinen Dateien enthalten. 
Das Problem war, dass ein Addon gefehlt hatte und daher die Installation fehlgeschlagen ist. Beim nächsten Installieren kam dann der Fehler.
